# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('widgets', 'widgets'),
        ('gui', 'gui'),
        ('db', 'db'),
        ('app_icon.png', '.'),
        ('dentalink.desktop', '.'),
        ('settings_config.json', '.'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtPrintSupport',
        'database',
        'db',
        'db.appointments',
        'db.clinical',
        'db.clinics',
        'db.connection',
        'db.crypto',
        'db.history',
        'db.patients',
        'db.procedural_graphics',
        'db.referrals',
        'db.seeding',
        'gui',
        'gui.login_window',
        'gui.main_window',
        'gui.styles',
        'gui.components',
        'gui.components.clickable_label',
        'gui.components.file_uploader',
        'gui.components.icon_helpers',
        'gui.dialogs',
        'gui.dialogs.admin_auth_dialog',
        'gui.dialogs.first_launch_dialog',
        'gui.dialogs.forgot_password_dialog',
        'gui.dialogs.treatment_done_dialog',
        'gui.dialogs.universal_key_dialog',
        'gui.dialogs.version_history_dialog',
        'widgets',
        'widgets.dental_chart',
        'widgets.xray_viewer',
        'cryptography',
        'sqlite3',
        'json',
        'hashlib',
        'hmac',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='DentaLink',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.png',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=[],
    name='DentaLink',
)

